gameinsighter_project/gameinsighter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/',include('webapp.urls'))
]

gameinsighter_project/webapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path(r'',views.home,name='home'),
    path(r'game_details/<int:id>/',views.game_details,name='game_details'),
    path(r'blog/',views.blog,name='blogs'),
    path(r'games/',views.games,name='games'),
    path(r'contact/',views.contact,name='contact'),
    path(r'blog/single-blog',views.singleBlog,name='single-blog'),
    path(r'games/game_details/<int:id>/',views.game_details,name='one_game_details'),

]

gameinsighter_project/webapp/models.py
from django.db import models

# Create your models here.
class gameDetails(models.Model):
    Steam_ID = models.PositiveIntegerField()
    Game_Title = models.CharField(max_length=255)
    Genre = models.CharField(max_length=255)
    Release_Date = models.CharField(max_length=255)
    Publisher = models.CharField(max_length=255)
    Price = models.CharField(max_length=255)
    Languages = models.TextField()
    Descriptions = models.TextField()
    Mature_Content_Descriptions = models.TextField(null=True)
    System_Requirements = models.TextField()
    Metric_Critic_Score = models.CharField(max_length=64, null=True)
    Metric_Critic_Score_Link = models.TextField(null=True)
    Links = models.TextField()
    def __str__(self):
        return self.Game_Title
    class Meta:
        db_table = 'Game Detail'
        verbose_name = 'Game Detail'

gameinsighter_project/webapp/views.py
from django.shortcuts import render
from .get_images import *
from .get_iframelinks import get_graphs
from .get_reviews import get_reviews
import requests
import json
import datetime
from .models import gameDetails

def home(request):
    graphs=get_graphs("all_game")
    return render(request,'index.html',graphs)

def game_details(request, id):
    gdobj=gameDetails.objects.filter(Steam_ID=id)
    sys_req_1=gdobj.values('System_Requirements')[0].get('System_Requirements').split("$")
    sys_req_1=[i.lstrip() for i in sys_req_1]
    sys_req_2=[i.split(":") for i in sys_req_1]
    sys_req=[j for j in sys_req_2 if len(j) == 2]
    sys_req=dict(sys_req)
    details={
        "Name": gdobj.values('Game_Title')[0].get('Game_Title'),
        "Genre": gdobj.values('Genre')[0].get('Genre'),
        "Release Date": gdobj.values('Release_Date')[0].get('Release_Date'),
        "Publisher": gdobj.values('Publisher')[0].get('Publisher'),
        "Languages": gdobj.values('Languages')[0].get('Languages'),
        "Description": gdobj.values('Descriptions')[0].get('Descriptions'),
        "images": get_images(id),
        "graphs": get_graphs(id)
    }
    return render(request, "game-details.html", {'details':details, 'sys_req':sys_req, 'get_reviews':get_reviews(id)})

def blog(request):
    return render(request, "blog.html")

def games(request):
    return render(request, "games.html")

def contact(request):
    return render(request, "contact.html")

def singleBlog(request):
    return render(request, "single-blog.html")

gameinsighter_project/webapp/templates/base.html
<!doctype html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Game Insighter</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place favicon.ico in the root directory -->
    <link href="{%static 'webapp/images/favicon.bin' %}" type="img/x-icon" rel="shortcut icon">

    <!-- All css files are included here. -->
    <link rel="stylesheet" href="{% static 'webapp/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/qanto.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/bauhaus93.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/icofont.min.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/plugins.css'%}">
    <link rel="stylesheet" href="{% static 'webapp/css/style.css'%}">
    <!-- Modernizr JS -->
    <script src="{% static 'webapp/js/vendor/modernizr-2.8.3.min.js' %}"></script>
{% block style %} 
{% endblock style%}
</head>

<body>
    <div id="main-wrapper">
        <!--Header section start-->
        <header class="header header-static bg-black header-sticky bg-dark">
            <div class="menu-right">
                <div class="container-fluid">
                    <div class="container-1520 m-0">
                        <div class="featured-title">
                            <h2 style="color:white;justify-content:center;">GAME INSIGHTER</h2>
                        </div>
                    </div>
                    <div class="row" style="margin:0;">
                        <!--Menu start-->
                        <div class="col-lg-12 col-12 order-md-3 order-lg-2 d-flex justify-content-center ">
                            <nav class="main-menu menu-style-2">
                                <ul>
                                    <li><a href="{% url 'webapp:home' %}">Home</a></li>
                                    <li><a href="{% url 'webapp:games' %}">Games</a></li>
                                    <li><a href="#game_trailers">Game Videos</a></li>
                                    <li><a href="{% url 'webapp:blogs' %}">Blogs</a></li>
                                    <li><a href="{% url 'webapp:contact' %}">Contact</a></li>
                                    <div style="width: 160px;"></div>
                                </ul>
                            </nav>
                        </div>
                        <!--Menu end-->
                    </div>
                    <div class="row">
                        <div class="col-12 d-flex d-lg-none">
                            <div class="mobile-menu"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!--Header section end-->
        {% block body %}

        {% endblock body %}
        <footer class="footer-section style-2 section bg-dark">

            <div class="footer-top section pt-80 pt-lg-70 pt-md-60 pt-sm-50 pt-xs-40 pb-80 pb-lg-70 pb-md-60 pb-sm-15 pb-xs-40"
                style="color:black;">
                <div class="container container-1520">
                    <div class="row justify-content-lg-between">
                        <div class="col-xl-3 col-lg-2 col-md-3">
                            <div class="footer-widget">
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-9">
                            <div class="footer-widget">
                                <div class="footer-nav">
                                    <nav>
                                        <ul>
                                            <li><a href="#">forums</a></li>
                                            <li><a href="#">demo</a></li>
                                            <li><a href="#">support</a></li>
                                            <li><a href="#">terms & conditions</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-3 col-lg-4 col-md-12">
                            <div class="footer-widget">
                                <div class="footer-social">
                                    <span>follow us:</span>
                                    <ul>
                                        <li><a href="#"><i class="icofont-facebook"></i></a></li>
                                        <li><a href="#"><i class="icofont-twitter"></i></a></li>
                                        <li><a href="#"><i class="icofont-instagram"></i></a></li>
                                        <li><a href="#"><i class="icofont-youtube-play"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer-bottom border-color section">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="copyright text-center">
                                <p>Copyright &copy;2018 . All rights reserved.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    
<!-- Placed js at the end of the document so the pages load faster -->
<!-- All jquery file included here -->
<script src="{% static 'webapp/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'webapp/js/popper.min.js' %}"></script>
<script src="{% static 'webapp/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webapp/js/plugins.js' %}"></script>
<script src="{% static 'webapp/js/main.js' %}"></script>
</body>

</html>

gameinsighter_project/webapp/templates/blog.html
{% extends 'base.html' %}
{% load static %}

{%block body%}
    <!--Blog Area Start-->
    <div class="all-blog-area section pt-100 pt-lg-80 pt-md-70 pt-sm-60 pt-xs-50" style="margin-top:100px">
        <div class="container">
            <div class="row row-25">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-12">
                            <!--Single Blog Post Start-->
                            <div class="single-blog-post mb-30">
                                <div class="blog-img">
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large1.jpg' %}" alt=""></a>
                                </div>
                                <div class="blog-content">
                                    <h3><a href="{%url 'webapp:single-blog' %}">hidden secret of the elder scroll</a></h3>
                                    <p>Some of hiden secret of the  Elder Scroll is the most popular are ames that your can Latest Mega 2019 games offer you ioous league and also alow you to make smile and enjoy the game maek it easy</p>
                                    <div class="blog-bottom">
                                        <ul class="meta meta-border-bottom">
                                            <li><a href="#">Smith</a></li> 
                                            <li>15 Devember, 2018 </li>
                                            <li><a href="#">25 Comments</a></li>
                                        </ul>
                                        <a class="read-btn" href="{%url 'webapp:single-blog' %}">READ NOW <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!--Single Blog Post End-->
                        </div>
                        <div class="col-12">
                            <!--Single Blog Post Start-->
                            <div class="single-blog-post mb-30">
                                <div class="blog-video">
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large2.jpg' %}" alt=""></a>
                                    <a class="video-btn" href=""><i class="icofont-play-alt-2"></i></a>
                                </div>
                                <div class="blog-content">
                                    <h3><a href="{%url 'webapp:single-blog' %}">life has no limited speed, but it’s need for speed</a></h3>
                                    <p>Some of hiden secret of the  Elder Scroll is the most popular are ames that your can Latest Mega 2019 games offer you ioous league and also alow you to make smile and enjoy the game maek it easy</p>
                                    <div class="blog-bottom">
                                        <ul class="meta meta-border-bottom">
                                            <li><a href="#">Nicolus</a></li> 
                                            <li>10 Devember, 2018 </li>
                                            <li><a href="#">689 Comments</a></li>
                                        </ul>
                                        <a class="read-btn" href="{%url 'webapp:single-blog' %}">READ NOW <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!--Single Blog Post End-->
                        </div>
                        <div class="col-12">
                            <!--Single Blog Post Start-->
                            <div class="single-blog-post mb-30">
                                <div class="blog-img">
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large3.jpg' %}" alt=""></a>
                                </div>
                                <div class="blog-content">
                                    <h3><a href="{%url 'webapp:single-blog' %}">secret code, new adventure for the witcher 3</a></h3>
                                    <p>Some of hiden secret of the  Elder Scroll is the most popular are ames that your can Latest Mega 2019 games offer you ioous league and also alow you to make smile and enjoy the game maek it easy</p>
                                    <div class="blog-bottom">
                                        <ul class="meta meta-border-bottom">
                                            <li><a href="#">Carlos</a></li> 
                                            <li>13 Devember, 2018 </li>
                                            <li><a href="#">399 Comments</a></li>
                                        </ul>
                                        <a class="read-btn" href="{%url 'webapp:single-blog' %}">READ NOW <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!--Single Blog Post End-->
                        </div>
                        <div class="col-12">
                            <!--Single Blog Post Start-->
                            <div class="single-blog-post mb-30">
                                <div class="blog-img-slider">
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large4.jpg' %}" alt=""></a>
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large2.jpg' %}" alt=""></a>
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large3.jpg' %}" alt=""></a>
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-large1.jpg' %}" alt=""></a>
                                </div>
                                <div class="blog-content">
                                    <h3><a href="{%url 'webapp:single-blog' %}">life has no limited speed, but it’s need for speed</a></h3>
                                    <p>Some of hiden secret of the  Elder Scroll is the most popular are ames that your can Latest Mega 2019 games offer you ioous league and also alow you to make smile and enjoy the game maek it easy</p>
                                    <div class="blog-bottom">
                                        <ul class="meta meta-border-bottom">
                                            <li><a href="#">Albert</a></li> 
                                            <li>08 Devember, 2018 </li>
                                            <li><a href="#">125 Comments</a></li>  
                                        </ul>
                                        <a class="read-btn" href="{%url 'webapp:single-blog' %}">READ NOW <i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!--Single Blog Post End-->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="blog-pagination text-center">
                                <ul class="page-pagination">
                                    <li><a href="#"><i class="icofont-long-arrow-left"></i></a></li>
                                    <li><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">6</a></li>
                                    <li><a href="#"><i class="icofont-long-arrow-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Blog Area End-->
    
    <!--Projects section start-->
    <div class="newslatter-section newslatter-section-tow section pt-xs-50 pb-xs-50" style="margin-bottom: 200px;">
        <div class="container">
           
            <div class="row">
               <div class="col-12">
                   <!--News Latter Area Start-->
                   <div class="news-latter-area newslatter-black">
                       <div class="news-latter-box">
                           <h3>SUBSCRIBE OUR NEWSLETTER, GET ALL <br> LATEST NEWS, UPDATE, VIDEOS AND OFFERS </h3>
                           <form action="#">
                               <input type="text" placeholder="Enter your email here">
                           </form>
                       </div>
                   </div>
                   <!--News Latter Area End-->
               </div> 
            </div>
            
        </div>
        
    </div>
    <!--Projects section end-->
{% endblock body %}

gameinsighter_project/webapp/templates/single-blog.html
{% extends 'base.html' %}
{% load static %}

{%block body%}
    <!--Page Banner Area Start-->
    <div class="page-banner-area" style="background-image: url({% static 'webapp/images/bg/page-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="page-content text-center">
                        <h1>KINGS OF THE <br> WARRIORS</h1>
                        <a class="df-btn" href="#">Buy now</a>
                        <ul class="page-breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li>Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Page Banner Area End-->
    
    <!--Blog Area Start-->
    <div class="blog-details-area section pt-100 pt-lg-80 pt-md-70 pt-sm-60 pt-xs-50 pb-xs-50" style="margin-top: 100px;">
        <div class="container">
            <div class="row row-25">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-12">
                            <div class="blog-details">
                                <div class="blog-img">
                                    <a href="{%url 'webapp:single-blog' %}"><img src="{% static 'webapp/images/blog/blog-details-1.jpg' %}" alt=""></a>
                                    <div class="meta-box">
                                        <ul class="meta meta-border-bottom">
                                            <li><a href="#">Smith</a></li> 
                                            <li>15 Devember, 2018 </li>
                                            <li><a href="#">25 Comments</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="blog-content">
                                    <h3>latest version of angry birds released in 2019</h3>
                                    <p><strong>Need for Sped</strong> rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally tances occur in which toil and pain can procure him some great pleasure pleasure rationally encounter sequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain itsuse it is pain, but because occasionally circumstances occur in which toil and pain can procure </p>
                                    <p>Rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally tances occur in which toil and pain can procure him some great pleasure pleasure rationally encounte</p>
                                    <blockquote class="blockquote mt-30 mb-30">
                                        <p>Rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because  nally tances occur in which toil and pain can procure </p>
                                    </blockquote>
                                    <p>Rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or ues or desires to obtain pain of itself, because it is pain, but because occasionally tances occur in which toil and pain can procure him some great pleasure pleasure rationally encounte</p>
                                    <div class="blog-tags">
                                        <h5>Tags:</h5> 
                                        <a href="#">Games</a>
                                        <a href="#">Playstation</a>
                                        <a href="#">Xbox</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="blog-comment-wrap col">
                            <h4>Comments</h4>
                            <ul class="comment-list">
                                <li>
                                    <div class="single-comment">
                                        <div class="image"><img src="{% static 'webapp/images/blog/comment-1.jpg' %}" alt=""></div>
                                        <div class="content">
                                            <h5>sannai smith</h5>
                                            <div class="review-date">
                                                <span>30 Janurary, 2018</span>
                                                <a href="#" class="reply">Reply</a>
                                            </div>
                                            <p>Ationally encounter consequences that are extremely painful. Nor again is there me anyone who loves or pursues or desires to obtain pain</p>
                                        </div>
                                    </div>
                                    <ul class="children">
                                        <li>
                                            <div class="single-comment">
                                                <div class="image"><img src="{% static 'webapp/images/blog/comment-2.jpg' %}" alt=""></div>
                                                <div class="content">
                                                    <h5>Alica Nicolus</h5>
                                                    <div class="review-date">
                                                        <span>13 December, 2018</span>     
                                                        <a href="#" class="reply">Reply</a>
                                                    </div>
                                                    <p>Ationally encounter consequences that are extremely painful. Nor again is there me anyone who loves or pursues or desires to obtain pain</p>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <div class="single-comment">
                                        <div class="image"><img src="{% static 'webapp/images/blog/comment-1.jpg' %}" alt=""></div>
                                        <div class="content">
                                            <h5>Lisa Rose</h5>
                                            <div class="review-date">
                                                <span>10 December, 2018</span>
                                                <a href="#" class="reply">Reply</a>
                                            </div>
                                            <p>Ationally encounter consequences that are extremely painful. Nor again is there me anyone who loves or pursues or desires to obtain pain</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <h4>Leave a reply</h4>
                            <form action="#" class="comment-form">
                                <div class="row">
                                    <div class="col-md-6 col-12 mb-30">  
                                        <input type="text" name="name" placeholder="Name">
                                    </div>

                                    <div class="col-md-6 col-12 mb-30">   
                                        <input type="email" name="email" placeholder="Email">
                                    </div>

                                    <div class="col-12 mb-30">   
                                        <textarea name="message" placeholder="Message"></textarea>
                                    </div>

                                    <div class="col-12">
                                        <input type="submit" value="send now">
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="sidebar-area mt-sm-60 mt-xs-50">
                        <!--Single Sidebar Widget Start-->
                        <div class="single-sidebar-widget mb-45">
                            <h3>featured games</h3>
                            <div class="single-featured-game mb-20">
                                <div class="game-img">
                                    <a href="#"><img src="{% static 'webapp/images/banner/banner1.jpg' %}" alt=""></a>
                                </div>
                            </div>
                            
                        </div>
                        <br>
                        <div class="single-sidebar-widget mb-45">
                            <h3>follow us</h3>
                            <div class="sidebar-social">
                                <ul>
                                    <li><a class="facebook" href="#"><i class="icofont-facebook"></i></a></li>
                                    <li><a class="youtube" href="#"><i class="icofont-youtube-play"></i></a></li>
                                    <li><a class="instagram" href="#"><i class="icofont-instagram"></i></a></li>
                                    <li><a class="twitter" href="#"><i class="icofont-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Blog Area End-->
    
    <!--Projects section start-->
    <div class="newslatter-section newslatter-section-tow section pt-5 pt-lg-0 pt-sm-0 pt-xs-0 pb-xs-50" style="margin-bottom: 200px;">
        <div class="container">
           
            <div class="row">
               <div class="col-12">
                   <!--News Latter Area Start-->
                   <div class="news-latter-area newslatter-black">
                       <div class="news-latter-box">
                           <h3>SUBSCRIBE OUR NEWSLETTER, GET ALL <br> LATEST NEWS, UPDATE, VIDEOS AND OFFERS </h3>
                           <form action="#">
                               <input type="text" placeholder="Enter your email here">
                           </form>
                       </div>
                   </div>
                   <!--News Latter Area End-->
               </div> 
            </div>
            
        </div>
        
    </div>
    <!--Projects section end-->
    
{% endblock body %}